package com.whaley.biz.setting.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whaley.biz.setting.db.LocalVideoBean;

import com.whaley.biz.setting.db.LocalVideoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localVideoBeanDaoConfig;

    private final LocalVideoBeanDao localVideoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localVideoBeanDaoConfig = daoConfigMap.get(LocalVideoBeanDao.class).clone();
        localVideoBeanDaoConfig.initIdentityScope(type);

        localVideoBeanDao = new LocalVideoBeanDao(localVideoBeanDaoConfig, this);

        registerDao(LocalVideoBean.class, localVideoBeanDao);
    }
    
    public void clear() {
        localVideoBeanDaoConfig.clearIdentityScope();
    }

    public LocalVideoBeanDao getLocalVideoBeanDao() {
        return localVideoBeanDao;
    }

}
