package com.whaleyvr.biz.download.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whaleyvr.biz.download.db.DownloadBean;

import com.whaleyvr.biz.download.db.DownloadBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadBeanDaoConfig;

    private final DownloadBeanDao downloadBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadBeanDaoConfig = daoConfigMap.get(DownloadBeanDao.class).clone();
        downloadBeanDaoConfig.initIdentityScope(type);

        downloadBeanDao = new DownloadBeanDao(downloadBeanDaoConfig, this);

        registerDao(DownloadBean.class, downloadBeanDao);
    }
    
    public void clear() {
        downloadBeanDaoConfig.clearIdentityScope();
    }

    public DownloadBeanDao getDownloadBeanDao() {
        return downloadBeanDao;
    }

}
